### ISSUE TITLE
Implement Travis

### ISSUE THREAD

**Issue by jeff-zucker** [jeff-zucker/solid-file-client#120]

**Comment by Otto-AA** [comment]
I think it would also be useful to see if automated tests fail on different operating systems, because as mentioned in #130 they probably don't all run on windows (while they do work for me on linux).

As far as I see, travis currently has rather good support for linux and macOS, and the windows version also supports nodejs (so I guess it works, but not sure for that one). This would be the updated travis file:
```
language: node_js
node_js:
  - 12
os:
  - linux
  - osx
  - windows
script:
  - npm run test:ls
  - npm run test:file
```

**Comment by jeff-zucker** [comment]
I finally implemented Travis and, pretty much as expected, tests passed in Linux and Mac but failed in Windows.

**Comment by jeff-zucker** [comment]
@Otto-AA the travis on windows failed with this: any ideas?
```
'TEST_PREFIX' is not recognized as an internal or external command,
operable program or batch file.
```
