### ISSUE TITLE
createFolder() fails on attempt to create sub-folder in non-existant folder

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-file-client#22]
Uncaught (in promise) TypeError: Cannot read property 'substr' of null

This error appear with createFolder() when trying to create a folder on recursive mode
`../tiddlers/main/test` and nor `/main` nor `/test` do exist
readFile() returns 404 and then I try to create above.
No Pb with non recursive. Just uncatched error

error line `var file = location.substr(location.lastIndexOf('/') + 1)`

`export async function add(parentFolder, url, content, contentType) {
return new Promise((resolve, reject)=>{
  let link = '<http://www.w3.org/ns/ldp#Resource>; rel="type"';
  if (contentType === 'folder') {
    link = '<http://www.w3.org/ns/ldp#BasicContainer>; rel="type"';
    contentType = 'text/turtle';
  }
  const request = {
    method: 'POST',
    headers: { slug:url, link:link },
    body: content
  };
  if( typeof(contentType)!="undefined" || typeof(window)!="undefined") 
       request.headers["Content-Type"] = contentType;
    solid.auth.fetch(parentFolder, request).then( res => {
      var location = res.headers.get('location')
      var file = location.substr(location.lastIndexOf('/') + 1)
      resolve( parentFolder+file );
  },err=>{reject(err)});
 });
}
`

**Comment by jeff-zucker** [comment]
The current createFolder() is a file-based temporary method until I can include solid-recursive-copy which is rdflib based and won't have this particular problem.  My head is hurting trying to think of how to trap the error in the current version - we don't want to throw an error on "folder not found" because the whole point is creating a folder that isn't there.  If an answer comes to me, I'll fix the error trapping but this too may have to wait until an rdflib aware version is available.

**Comment by jeff-zucker** [comment]
@bourgeoa is this still a problem, if not, can you close it?

**Comment by jeff-zucker** [comment]
Fixed in version 1.0.0.
