### ISSUE TITLE
Copy folder only copies contents

### ISSUE THREAD

**Issue by Otto-AA** [jeff-zucker/solid-file-client#27]
As far as I've seen, the copyFolder function only copies the contents of a folder to an already existing one. For me it would seem more intuitive, that the function also creates a new containing folder at the target destination if it doesn't exist yet.

So I would suggest to either change that behavior (create the folder if it doesn't exist before copying), or to mention it in the documentation/the function name (e.g. `copyFolderContents`).

**Comment by bourgeoa** [comment]
I had at first the same feeling, but now I prefer the actual way and check if the destination folder do exist. For example you would need a recursive create.

**Comment by Otto-AA** [comment]
Ok, I will close this now as it doesn't appear to be a bug. As mentioned before, I would suggest to add this to the documentation or change the function name.

**Comment by jeff-zucker** [comment]
Thanks. Now that solid-auth-cli is included in rdflib, I can submit my solid-recursive-copy stuff which will mean a much more powerful copyFolder().  I prefer to wait until I can use that in solid-file-client rather than tweaking the current version.  But I really appreciate all your suggestions.  Thanks!
