### ISSUE TITLE
Please bump rdflib to 1.0

### ISSUE THREAD

**Issue by CxRes** [jeff-zucker/solid-file-client#74]
I am having trouble bundling sub-dependencies of the older rdflib (eventhough rdflib 0.20.3 is a couple of months old, it uses a two year old version of jsonld 0.4.12 which uses some strange requires). If it does not affect the code, please consider upgrading!!!!

**Comment by jeff-zucker** [comment]
@CxRes The upcoming new version of solid-file-client (due out in a week or two) will decouple rdflib, meaning each user will include rdflib on their own rather than it being part of the bundle.  In the meantime, you can download or clone the library, update rdflib in the cloned node_modules, and use npm install to create a new bundle with the newest rdflib.

**Comment by bourgeoa** [comment]
@CxRes 
I tested all versions 1.0.0 up to version 1.0.3. They all fail tests on solid-file-client
So I shall not try to push a new version on these bases.

**Comment by jeff-zucker** [comment]
Closing this - the new Solid-File-Client v.1.x does not use rdflib.
