### ISSUE TITLE
Authentication works on solid.community but not on inrupt.net

### ISSUE THREAD

**Issue by Okilele-newbie** [jeff-zucker/solid-file-client#88]
![log in to solid community](https://user-images.githubusercontent.com/57221306/69495005-3abb0200-0ec2-11ea-92ca-ea7187e30ae4.png)
First step : I am asked to log in solid community as I cleared all data of the application (localhost:3000) and the log in pane should not know on which server I want to log in. But may be this is just a questions of label but the url of the popup also targets solid.community ...
Then: 
![Error on Inrupt](https://user-images.githubusercontent.com/57221306/69495022-7ce44380-0ec2-11ea-9348-cd87466eaf59.png)
I get a 401 error as you can see the solid.gile.client.popupLogin() method as logged me correctly.
Related to previous messages about multi auth-client (I have them when on solid.community server without any trouble) and also solid-file-client listening to solid.community as I am logged on inrupt.net ?

**Comment by jeff-zucker** [comment]
@Okilele-newbie  solid-auth-client has had trouble with multiple active logins and I'm not sure it is possible at the moment.  I'll check and see if it's something that can be fixed in solid-file-client or not.  Best temporary fix is to logout from one server before logging in to the other. Thanks for reporting.  @bourgeoa and @Otto-AA - any thoughts?

**Comment by jeff-zucker** [comment]
This is a solid-auth-client issue, Solid-File-Client no longer handles the login directly.
